APPLY_FIXES: all
FILTER_REGEX_EXCLUDE: (pnpm-lock.yaml)

DISABLE_LINTERS:
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - TYPESCRIPT_STANDARD
  - JSON_JSONLINT
  - YAML_YAMLLINT

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
