ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - ACTION_ACTIONLINT
  - SPELL_VALE
  - SPELL_PROSELINT
APPLY_FIXES:
  - MARKDOWN_MARKDOWNLINT

CLEAR_REPORT_FOLDER: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: false
ACTION_ACTIONLINT_ARGUMENTS: -color --shellcheck=
