pull_request_rules:
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued

  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = automerge
      - or:
        - author = dependabot[bot]
        - author = KubeArchitectBot
    actions:
      merge:

  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - '-closed'
    actions:
      label:
        toggle:
          - conflict