export default {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'IT Security',
      items: [
        {
          type: 'autogenerated',
          dirName: 'it-security', // Generate sidebar slice from docs/it-security
        },
      ],
    },
    {
      type: 'category',
      label: 'Kubernetes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'kubernetes', // Generate sidebar slice from docs/kubernetes
        },
      ],
    },
    {
      type: 'category',
      label: 'Linux',
      items: [
        {
          type: 'autogenerated',
          dirName: 'linux', // Generate sidebar slice from docs/linux
        },
      ],
    },
    {
      type: 'category',
      label: 'Windows',
      items: [
        {
          type: 'autogenerated',
          dirName: 'windows', // Generate sidebar slice from docs/linux
        },
      ],
    },
  ],
};
