name: Create Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc # v1

    - run: bun install
    - run: bun run build

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v2.0.0
      with:
        package-path: ./package.json
        release: true

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v2.0.0
      if: steps.create_tag.outputs.successful
      with:
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (RelativeSure|KubeArchitectBot|dependabot\[bot\]|Renovate Bot)
        filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)
        template: |
          ## Bugs
          {{fix}}
          ## Feature
          {{feat}}
          ## Improve
          {{refactor,perf,clean}}
          ## Misc
          {{chore,style,ci||🔶 Nothing change}}
          ## Unknown
          {{__unknown__}}

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      if: steps.create_tag.outputs.successful
      with:
        skipIfReleaseExists: true
        artifacts: docs/*
        artifactContentType: markdown
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}
