name: Create Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**/*.yml'
      - '.gitignore'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc # v1

    - run: bun install
    - run: bun run build

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@main
      with:
        package-path: ./package.json
        release: true

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      if: steps.create_tag.outputs.successful
      with:
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (RelativeSure|KubeArchitectBot|dependabot\[bot\]|Renovate Bot)
        filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)

    - name: Generate Changelog
      uses: jaywcjlove/create-tag-action@main
      if: steps.create_tag.outputs.successful
      with:
        version: ${{steps.create_tag.outputs.version}}
        release: true
        body: |
          ```bash
          npm i @uiw/react-heat-map@${{steps.create_tag.outputs.versionNumber}}
          ```

          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}
