name: Create Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1.2.0

    - uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
      id: bun-cache
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - run: bun install
    - run: bun run build

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@4ab0a9ecf81779bc84c9b1ab8b3177a31828d6d3 # v2.0.0
      with:
        package-path: ./package.json
        release: true

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@a495456e2cfc62aa361eded8ca659d27b5fe6c61 # v2.0.0
      if: steps.create_tag.outputs.successful
      with:
        head-ref: ${{steps.create_tag.outputs.version}}
        template: |
          ## Bugs
          {{fix}}
          ## Feature
          {{feat}}
          ## Improve
          {{refactor,perf,clean}}
          ## Misc
          {{chore,style,ci||🔶 Nothing change}}
          ## Unknown
          {{__unknown__}}

    - name: Create Release
      uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
      if: steps.create_tag.outputs.successful
      with:
        allowUpdates: true
        artifacts: "docs/**/*.md,docs/**/*.mdx"
        artifactContentType: markdown
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}
