name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0/30 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@5e224f3a02c7ce9cadc83f82d65f1b6dd73876c1 # v39.0.3
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ secrets.KUBEARCHITECTBOT_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
