name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0/30 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ secrets.KUBEARCHITECTBOT_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
